### ISSUE TITLE
Run kafka-backup in SSL mode

### ISSUE THREAD

**Issue by SteveGit007** [itadventurer/kafka-backup#91] opened 2020-06-05 13:59 UTC
Hi,
Have you example of a docker-compose to execute Kafka-Backup in SSL mode ?
Thanks

**Comment by itadventurer** [comment] 2020-06-06 18:54
Hey,
No I do not have such an example but there is nothing special about Kafka Backup when it applies to SSL. You just need to use the `--command-config` option when using `backup-standalone.sh` and `restore-standalone.sh`.
See https://github.com/itadventurer/kafka-backup/issues/12#issuecomment-616194718 for an example with SASL SCRAM.

Duplicate of #12. I would be very happy if you could write down your findings there or in a PR. Will close this issue.

**Closed by itadventurer** 2020-06-06 18:54 UTC
