### ISSUE TITLE
kafka-backup sink task is failing

### ISSUE THREAD

**Issue by jay7x** [itadventurer/kafka-backup#11] opened 2020-01-17 10:13 UTC
I'm playing with kafka-backup using SSL and it seems failing at very beginning of actual backup.
This happens after 
```
...
[2020-01-17 10:05:31,879] INFO Resetting offset for tenancity.chrono-billable-datasink-0 based upon existing consumer group offsets or, if there are none, the consumer's 'auto.offset.reset' value. (de.azapps.kafkabackup.sink.BackupSinkTask:93)
[2020-01-17 10:05:31,879] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Seeking to offset 266640 for partition greenie.raw-data-6 (org.apache.kafka.clients.consumer.KafkaConsumer:1564)
[2020-01-17 10:05:31,880] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Seeking to offset 251914 for partition greenie.raw-data-1 (org.apache.kafka.clients.consumer.KafkaConsumer:1564)
[2020-01-17 10:05:31,880] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Seeking to offset 34697 for partition tenancity.invalid-post-validation-4 (org.apache.kafka.clients.consumer.KafkaConsumer:1564)
[2020-01-17 10:05:31,880] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Seeking to offset 486093 for partition tenancity.billable-meter-data-3 (org.apache.kafka.clients.consumer.KafkaConsumer:1564)
[2020-01-17 10:05:37,709] ERROR WorkerSinkTask{id=chrono-qa-backup-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
java.lang.NullPointerException
        at de.azapps.kafkabackup.common.record.RecordSerde.write(RecordSerde.java:98)
        at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:72)
        at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
        at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[2020-01-17 10:05:37,750] INFO WorkerSinkTask{id=chrono-qa-backup-sink-0} Committing offsets synchronously using sequence number 1: [...LARGE OUTPUT HERE...]
[2020-01-17 10:05:37,788] ERROR WorkerSinkTask{id=chrono-qa-backup-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at de.azapps.kafkabackup.common.record.RecordSerde.write(RecordSerde.java:98)
        at de.azapps.kafkabackup.common.segment.SegmentWriter.append(SegmentWriter.java:72)
        at de.azapps.kafkabackup.common.partition.PartitionWriter.append(PartitionWriter.java:57)
        at de.azapps.kafkabackup.sink.BackupSinkTask.put(BackupSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        ... 10 more
[2020-01-17 10:05:37,789] ERROR WorkerSinkTask{id=chrono-qa-backup-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2020-01-17 10:05:37,794] INFO Stopped BackupSinkTask (de.azapps.kafkabackup.sink.BackupSinkTask:128)
[2020-01-17 10:05:37,804] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Revoke previously assigned partitions [... LARGE OUTPUT HERE ...]
[2020-01-17 10:05:37,805] INFO [Consumer clientId=connector-consumer-chrono-qa-backup-sink-0, groupId=connect-chrono-qa-backup-sink] Member connector-consumer-chrono-qa-backup-sink-0-13ce20de-a2c0-4ce8-afcf-b08b11dae1fd sending LeaveGroup request to coordinator spdachronokafkaq1.node.spda:9093 (id: 2147483646 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:916)
```

Then process still persists but seems doing nothing...
I'm using Kafka 2.4 build with scala 2.12. Connection to kafka cluster is made via SSL but locally on one of cluster nodes. Kafka and kafka-backup are both in docker containers in host network. Both containers are based on adoptopenjdk/openjdk11:ubuntu-jre.

**Comment by itadventurer** [comment] 2020-01-17 10:24
Hmmm… This is weird. Caused by a nullpointer in https://github.com/itadventurer/kafka-backup/blob/master/src/main/java/de/azapps/kafkabackup/common/record/RecordSerde.java#L98 .
I wanted to take a closer look at kafka-backup next week. I developed it before Kafka 2.4 was released so I assume that there might be a few compatibility issues as maybe some APIs changed.

**Comment by jay7x** [comment] 2020-01-17 10:25
Just confirmed it happens w/o SSL too JFYI. Thank you anyway! I'll postpone my backup task then..

**Comment by itadventurer** [comment] 2020-01-22 11:53
Before we continue investigating further: Could you try to build it again with the new master branch? I have updated the dependencies and fixed some smaller glitches.

**Comment by jay7x** [comment] 2020-01-23 04:14
Just tried w/o SSL and it seems working! Thank you!
Not sure about SSL though, as I dropped contents of backup-dir. I was thinking it will redo backup but it seems it's continuing it from last point. Is there any way to do fresh backup (reset offsets again somehow)?

**Comment by jay7x** [comment] 2020-01-23 04:43
Well, backup via SSL seems working too. Though I'd like to know how to reset offsets anyway :-D

**Comment by itadventurer** [comment] 2020-01-29 19:46
Sorry, forgot to answer that: There is currently no documentation for that, so currently you have two ways:

1. See comments in [BackupSinkTask](https://github.com/itadventurer/kafka-backup/blob/master/src/main/java/de/azapps/kafkabackup/sink/BackupSinkTask.java#L82)
2. For now the easier approach is to simply delete the old connector and create a new one with another name ;)

Added this to the documentation issue: #2 

I will close this issue for now. Feel free to open a new one if you have more questions

**Closed by itadventurer** 2020-01-29 19:46 UTC
