### ISSUE TITLE
PartitionWriter Initialisation against kafka start offset

### ISSUE THREAD

**Issue by jpopol** [itadventurer/kafka-backup#5] opened 2019-08-19 09:31 UTC
In `PartitonWriter` constructor I can see the following:
` currentSegment = new SegmentWriter(topic, partition, 0, topicDir);
  // do not forget to add the current segment to the partition index. Even if it is empty
 partitionIndex.appendSegment(currentSegment.filePrefix(), 0);` 

You hard-code startOffset to 0, ideally  for topics that have a ttl so don't start at 0 anymore we would like to see the startoffset being another number.

What would be according to you the best way to handle this ?
 
Also when a set of file have been created with 0 as starting point when the earliest offset if for example 1234. Can the partition cli restore task use the content of the file first index rather than the name regex of the file ?

**Comment by itadventurer** [comment] 2019-08-23 08:10
This should not be an issue at all. This piece of code just checks whether there is already a Segment for the backup data and if not creates a new with a start offset of `0` – This influences only the name of the file – the first record in that file will have the original offset.

During restore the names of the files are ignored too – just the content matters. The files just need some names and using the start offset is a reasonable choice since Kafka is also doing the same ;)

The only thing to note here is that if you are backing up a topic and you write old segments to another storage system – always keep at least the latest one in the directory where `kafka-backup` is writing its data to. 

Hope that this helps ;)

**Comment by itadventurer** [comment] 2020-01-22 11:55
Closing this issue as this is expected behaviour

**Closed by itadventurer** 2020-01-22 11:55 UTC
