### ISSUE TITLE
Option to exit process after the backup is completed?

### ISSUE THREAD

**Issue by akamensky** [itadventurer/kafka-backup#53] opened 2020-04-08 09:40 UTC
I would love to run this as a cli tool. Finally figured out configuration to run this with connect-standalone, but it hangs around after the backup is done, so I need to interactively Ctrl-C it to stop the process, which results in:

```
[2020-04-08 09:35:45,458] ERROR Plugin class loader for connector: 'de.azapps.kafkabackup.sink.BackupSinkConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@62e20a76 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:165)
```

**Comment by itadventurer** [comment] 2020-04-11 14:31
Duplicate of #46. Actually thats a good idea to run it as a cli tool! Thank you for that idea. If you have other ideas please add them to #46

**Closed by itadventurer** 2020-04-11 14:31 UTC
